### ISSUE TITLE
uaac not in PATH

### ISSUE THREAD

**Issue by vChrisR** [EngineerBetter/pcfops-docker#5] opened 2022-09-21 09:50 UTC
uaac is not in the PATH var anymore.

**Comment by marcinkubica** [comment] 2023-01-04 13:00
Hi @vChrisR 
The problem is now fixed in https://github.com/EngineerBetter/pcfops-docker/commit/449afcfb0bd176ade9340921485b6b7735b6a5ef

Also, https://github.com/EngineerBetter/pcfops-docker/commit/ce27e82767c7e31f2056fadaff3bc2ca8110f671 fixes the issue when we were not thoroughly testing the existence of binaries.

**Closed as completed** 2023-01-05 09:27 UTC
Labels: bug, enhancement
